#!/bin/sh

rm -r -f output
mkdir output

#compile coffee-script
./node_modules/.bin/coffee --compile --output output/js/ src/

#make bindit.js
cat output/js/BindIt.js             >> output/bindit.js

#Utils
cat output/js/utils/Logger.js       >> output/bindit.js
cat output/js/utils/Hash.js         >> output/bindit.js

#Binding
cat output/js/EventDispatcher.js    >> output/bindit.js
cat output/js/Model.js              >> output/bindit.js
cat output/js/ModelArray.js         >> output/bindit.js
cat output/js/DOMEventDispatcher.js >> output/bindit.js
cat output/js/View.js               >> output/bindit.js
cat output/js/dom.js                >> output/bindit.js
cat output/js/Template.js           >> output/bindit.js

#View
cat output/js/view/ListView.js      >> output/bindit.js
cat output/js/view/Input.js         >> output/bindit.js
cat output/js/view/Button.js        >> output/bindit.js
cat output/js/view/Text.js          >> output/bindit.js
cat output/js/view/Checkbox.js      >> output/bindit.js
cat output/js/view/Select.js        >> output/bindit.js
cat output/js/view/Radio.js         >> output/bindit.js

#make bindit-min.js
java -jar libs/compiler.jar --js output/bindit.js --js_output_file output/bindit-min.js --compilation_level SIMPLE_OPTIMIZATIONS